FROM alpine as certs
RUN apk update && apk add ca-certificates

FROM  --platform=linux/arm64 ubuntu

MAINTAINER Parth Mudgal <artpar@gmail.com>
WORKDIR /

COPY --from=certs /etc/ssl/certs /etc/ssl/certs

COPY daptin-linux-arm64 /opt/L3m0nSo/Memories
RUN chmod +x /opt/L3m0nSo/Memories
RUN ls -lah /opt/L3m0nSo/Memories

#COPY daptin-linux-arm64 /bin/daptin
#RUN chmod +x /bin/daptin
#RUN ls -lah /bin/daptin

EXPOSE 8080
ENTRYPOINT ["/opt/L3m0nSo/Memories", "-runtime", "release", "-port", ":8080"]